name: Build Arch Live ISO

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux@sha256:2eb1a56a6036b1f70e63ca714814fe304a8f20d29ab425b4f056f34508500000
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arch Live ISO Build
        run: |
          df -h
          pacman -Sy --noconfirm archiso wget which
          /usr/bin/env bash -eux $(which mkarchiso) -v . || df -h
          iso_file=$(find out/ -name '*.iso' | head -n 1)
          date_str=$(date +%Y%m%d%H%M%S)
          arch=$(uname -m)
          mv "$iso_file" "gershwin-on-arch-${date_str}-${arch}.iso"
          
        shell: sh

      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          ls -lh *.iso
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh *.iso
